import type { Metadata } from "next";
import "./globals.css";
import logo from "./logo.png";

export const metadata: Metadata = {
	title: "Product Hunt Clone",
	description: "Generated by create next app",
	icons: `${logo.src}`,
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body>{children}</body>
		</html>
	);
}
